services:
  web-scraper:
    build:
      context: ./scraper_service/
      dockerfile: Dockerfile
    env_file: ./scraper_service/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file: ./scraper_service/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data/

volumes:
  postgres_data: